/*:
# Inductance
 This page features a circuit with a resistor-inductor circuit. A capacitor is passive circuit component and it has the ability to store electric charge and oppose the current through it using the magnetic field generated by its coils. The voltage across a inductor is equal to the inductance of the inductor and the current change per unit time.

![Equation for Inductance](Inductance.PNG)
 
**Task:** Induce My Current
 1. Tap `Run My Code` button on the right.
 2. Click on the `Solve` button.  What is the voltage across the inductor?
 3. Tap on the `Next Time Step` button. What happens to voltage and current? Does it increase or decrease?
 4. Change the value of the inductance? How does it affect the rate of change of the voltage and current?

 In a direct current circuit, the inductor would have stored its full capacity after five time constants, thus, the inductor will cause the circuit act as an open circuit.

Go to the [Next Page](@next) where it will be your time to shine.
*/
import SwiftUI
import PlaygroundSupport

let preset: CircuitPreset = .resistorInductor
PlaygroundPage.current.wantsFullScreenLiveView = true
PlaygroundPage.current.needsIndefiniteExecution = true
PlaygroundPage.current.setLiveView(
    MainView()
        .environmentObject(CircuitEnvironment(circuit: preset.circuit))
        .ignoresSafeArea()
)
